/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    'gallery-items': GalleryItem;
    'hero-slides': HeroSlide;
    'showcase-items': ShowcaseItem;
    reviews: Review;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    'showcase-items': ShowcaseItemsSelect<false> | ShowcaseItemsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  labelEn: string;
  labelZh?: string | null;
  subEn?: string | null;
  subZh?: string | null;
  /**
   * Image shown on this category's card on /work. If left empty, the first gallery item's image is used.
   */
  coverImage?: (number | null) | Media;
  /**
   * Auto-filled from the English label if left blank. Used as the #anchor on /work.
   */
  slug?: string | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  title: string;
  slug?: string | null;
  /**
   * Pick one or more — this image shows in every category you select.
   */
  category: (number | Category)[];
  /**
   * Lower numbers show first within a category.
   */
  order?: number | null;
  image: number | Media;
  /**
   * Describes the image for screen readers and SEO. Falls back to the Title if blank.
   */
  alt?: string | null;
  /**
   * Short description shown under the enlarged image.
   */
  caption?: string | null;
  /**
   * Malaysian state / territory.
   */
  location?:
    | (
        | 'Johor'
        | 'Kedah'
        | 'Kelantan'
        | 'Melaka'
        | 'Negeri Sembilan'
        | 'Pahang'
        | 'Penang'
        | 'Perak'
        | 'Perlis'
        | 'Sabah'
        | 'Sarawak'
        | 'Selangor'
        | 'Terengganu'
        | 'Kuala Lumpur'
        | 'Labuan'
        | 'Putrajaya'
      )
    | null;
  businessType?:
    | (
        | 'Restaurant'
        | 'Cafe'
        | 'Bakery'
        | 'Bar / Pub'
        | 'Kopitiam / Mamak'
        | 'Retail Shop'
        | 'Boutique / Fashion'
        | 'Minimart / Convenience Store'
        | 'Supermarket / Grocery'
        | 'Hair Salon'
        | 'Beauty / Spa'
        | 'Barbershop'
        | 'Clinic / Medical'
        | 'Dental Clinic'
        | 'Pharmacy'
        | 'Gym / Fitness'
        | 'Automotive / Workshop'
        | 'Car Wash'
        | 'Hotel / Hostel'
        | 'Education / Tuition Centre'
        | 'Office / Corporate'
        | 'Electronics Store'
        | 'Hardware Store'
        | 'Gaming / Esports'
        | 'Property / Real Estate'
        | 'Bank / Financial Services'
        | 'other'
      )
    | null;
  /**
   * Shown only when Business Type is set to Other.
   */
  businessTypeOther?: string | null;
  baseMaterial?:
    | (
        | 'Polycarbonate Base'
        | 'Aluminum Ceiling Panel Base'
        | 'Acrylic Base'
        | 'PVC Base'
        | 'ACP Base'
        | 'Wall Base'
        | 'Billboard Base'
        | 'Custom Base'
        | 'Other Base'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Big rotating images at the top of the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  image: number | Media;
  /**
   * Describes the image for screen readers and SEO.
   */
  alt?: string | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos + details shown in the home page "Who Is It For?" grid.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showcase-items".
 */
export interface ShowcaseItem {
  id: number;
  title: string;
  image: number | Media;
  /**
   * Short line shown under the enlarged image.
   */
  description?: string | null;
  /**
   * Malaysian state / territory.
   */
  location?:
    | (
        | 'Johor'
        | 'Kedah'
        | 'Kelantan'
        | 'Melaka'
        | 'Negeri Sembilan'
        | 'Pahang'
        | 'Penang'
        | 'Perak'
        | 'Perlis'
        | 'Sabah'
        | 'Sarawak'
        | 'Selangor'
        | 'Terengganu'
        | 'Kuala Lumpur'
        | 'Labuan'
        | 'Putrajaya'
      )
    | null;
  /**
   * e.g. 10ft x 3ft
   */
  size?: string | null;
  businessType?:
    | (
        | 'Restaurant'
        | 'Cafe'
        | 'Bakery'
        | 'Bar / Pub'
        | 'Kopitiam / Mamak'
        | 'Retail Shop'
        | 'Boutique / Fashion'
        | 'Minimart / Convenience Store'
        | 'Supermarket / Grocery'
        | 'Hair Salon'
        | 'Beauty / Spa'
        | 'Barbershop'
        | 'Clinic / Medical'
        | 'Dental Clinic'
        | 'Pharmacy'
        | 'Gym / Fitness'
        | 'Automotive / Workshop'
        | 'Car Wash'
        | 'Hotel / Hostel'
        | 'Education / Tuition Centre'
        | 'Office / Corporate'
        | 'Electronics Store'
        | 'Hardware Store'
        | 'Gaming / Esports'
        | 'Property / Real Estate'
        | 'Bank / Financial Services'
        | 'other'
      )
    | null;
  baseMaterial?:
    | (
        | 'Polycarbonate Base'
        | 'Aluminum Ceiling Panel Base'
        | 'Acrylic Base'
        | 'PVC Base'
        | 'ACP Base'
        | 'Wall Base'
        | 'Billboard Base'
        | 'Custom Base'
        | 'Other Base'
      )
    | null;
  /**
   * Shown only when Business Type is set to Other.
   */
  businessTypeOther?: string | null;
  price?:
    | (
        | 'RM1,000++'
        | 'RM2,000++'
        | 'RM3,000++'
        | 'RM4,000++'
        | 'RM5,000++'
        | 'RM6,000++'
        | 'RM7,000++'
        | 'RM8,000++'
        | 'RM9,000++'
        | 'RM10,000++'
        | 'custom'
      )
    | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  /**
   * Shown only when Price is set to Custom.
   */
  priceCustom?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer reviews shown on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  author: string;
  /**
   * 1 to 5 stars.
   */
  rating: number;
  text?: string | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'showcase-items';
        value: number | ShowcaseItem;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  labelEn?: T;
  labelZh?: T;
  subEn?: T;
  subZh?: T;
  coverImage?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  order?: T;
  image?: T;
  alt?: T;
  caption?: T;
  location?: T;
  businessType?: T;
  businessTypeOther?: T;
  baseMaterial?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "showcase-items_select".
 */
export interface ShowcaseItemsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  description?: T;
  location?: T;
  size?: T;
  businessType?: T;
  baseMaterial?: T;
  businessTypeOther?: T;
  price?: T;
  order?: T;
  priceCustom?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  author?: T;
  rating?: T;
  text?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Social media links used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * e.g. https://facebook.com/yourpage
   */
  facebook?: string | null;
  /**
   * e.g. https://instagram.com/yourhandle
   */
  instagram?: string | null;
  /**
   * e.g. https://tiktok.com/@yourhandle
   */
  tiktok?: string | null;
  /**
   * Link to your Google reviews page (the badge links here).
   */
  googleReviewsUrl?: string | null;
  /**
   * e.g. "4.8"
   */
  googleRating?: string | null;
  /**
   * e.g. "50"
   */
  googleReviewCount?: string | null;
  /**
   * Format "GTM-XXXXXXX". If you load GA4 through GTM, leave the GA4 field below empty.
   */
  gtmId?: string | null;
  /**
   * Format "G-XXXXXXXXXX". Only fill this if you are NOT already loading GA4 via Tag Manager.
   */
  ga4Id?: string | null;
  /**
   * The content value from the "google-site-verification" meta tag Google gives you.
   */
  googleSiteVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  facebook?: T;
  instagram?: T;
  tiktok?: T;
  googleReviewsUrl?: T;
  googleRating?: T;
  googleReviewCount?: T;
  gtmId?: T;
  ga4Id?: T;
  googleSiteVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}